### ISSUE TITLE
Toggling windowed mode radio button breaks custom resolutions

### ISSUE THREAD

**Issue by eddebaby** [dkfans/keeperfx-launcherwx#4]
Moving from Loobinex/keeperfx-unofficial#171

If you select the Windowed Mode radio button, you are then unable to select/deselect or modify the custom resolutions. Switching back to fullscreen doesn't work, you must restart the Settings Editor.

Adjust the size of the window will fix this issue until you next toggle the screen mode.

Also, the top-left option (currently 320x200x8) can only be toggled by clicking the label, rather than the checkbox.

Appears to be UI only, existing selected resolutions are not removed when saving the settings, and can be used in-game.

**Comment by eddebaby** [comment]
I haven't figured out the cause yet, but:
- This seems to be connected to repeat calls to _resIngameBox->CreateOptionCheckboxes_ from _GameSettings::ChangeResolutionOptions_
- _ChangeResolutionOptions(2);_ in _GameSettings::GameSettings_ causes 320x200x8 to be uncheckable
- _ChangeResolutionOptions(event.GetInt());_ in _GameSettings::OnScreenCtrlChange_ causes the 3 editable resolutions to be uncheckable (each time it is run, see next point)
- both of these errors can be cleared by changing the height (not the width) of the window. If you only change the height a bit, then the checkboxes are only clickable in a very small location.

**Comment by eddebaby** [comment]
I still cannot trace the issue yet, but it seems to be related to trashing and rebuilding the array of checkboxes. Something is just not getting set correctly after the 1st time around.

- You _**can**_ press the 320x200x8 option, if you click the label rather than the actual checkbox (From testing, there could be another object on top/conflicting, as when objects are not placed in the sizer, they are cropped in to a small square in the top left of the window)
- The "fix" for the custom resolutions seems to be triggered when the checkboxes move on screen. Possibly the clickable area position is not correctly set/reset?
- Workaround: I have an alternate **UpdateOptionCheckboxes** function, to be used instead of repeat calls to **CreateOptionCheckboxes**, but I will investigate a bit further, before just submitting the new functionality (it needs some more testing too).

**Comment by eddebaby** [comment]
Fixed. It was an orphaned child sizer obscuring the regenerated radioboxes.

This was the function I was working on, in-case it is ever of interest:
```
void wxCheckRadioBox::UpdateOptionCheckboxes(const wxString *values_arr, const wxString *val_labels_arr, size_t values_num, size_t custom_num)
{
    {
        size_t i;
        size_t norm_num = rbCheckboxes.size() - rbTextCtrls.size();
        for(i=0; i < values_num-custom_num; i++)
        {
            
            rbValues[i] = values_arr[i];
            rbValLabels[i] = val_labels_arr[i];
            rbCheckboxes[i]->SetLabel(rbValLabels[i]);
            //rbCheckboxes[i]->SetValue(rbValues[i]);
        }
        for(; i < values_num; i++)
        {
            rbValues[i] = values_arr[i];
            rbValLabels[i] = val_labels_arr[i];
            rbCheckboxes[i]->SetLabel("cust:");
            //rbCheckboxes[i]->SetValue(rbValues[i]);
            if (rbCheckboxes[i]->GetValue())
                rbTextCtrls[i-norm_num]->SetValue(rbValues[i]);
            else
                rbTextCtrls[i-norm_num]->SetValue(rbValLabels[i]);
        }
        if (select_num >= select_limit) {
            SetAllUncheckedEnabled(false);
        }
        else {
            SetAllUncheckedEnabled(true);
        }
        rbPanel->Update();
    }
}
```

Due to the way this works with the "Selected" resolutions, being that when you select mixed mode, it will track your options differently (this could be revamped as neither this, nor the existing behaviour are ideal (on switching between mixed mode/fullscreen/windowed). This is so niche though... I workaround is to have 4 custom text boxes, this should work well with existing method and this method.

The following code is needed to correct the locking of the checkboxes/textboxes:
```
void wxCheckRadioBox::SetAllUncheckedEnabled(bool nstate)
{
    size_t i;
    size_t norm_num = rbCheckboxes.size() - rbTextCtrls.size();
    for (i=0; i < rbCheckboxes.size(); i++)
    {
        if (!rbCheckboxes[i]->GetValue()) {
            rbCheckboxes[i]->Enable(nstate);
        }
        else {
            rbCheckboxes[i]->Enable(true);
        }
    }
                                                               
    for (i=0; i < rbTextCtrls.size(); i++)
    {
        if (!rbCheckboxes[i+norm_num]->GetValue()) {
            rbTextCtrls[i]->Enable(nstate);
        }
        else {
            rbTextCtrls[i]->Enable(true);
        }
        
    }
}
```

**Comment by Loobinex** [comment]
I see no remaining work. Fixed->closed.
